### ISSUE TITLE
work nicely with oh-my-zsh 

### ISSUE THREAD

**Issue by kilianc** [SublimeLinter/SublimeLinter-jshint#10]
nvm uses the oh-my-zsh plugin to load and not .zshenv

**Comment by cloverich** [comment]
@aparajita  The comments here were very helpful, but I had to do something slightly different. With a clean install of OSX Yosemite:  

1. Installed zsh, oh-my-zsh
2. Installed nvm
3. Tell my shell to use a specific node install on load

After Step 2, I found the following in my `~/.zshrc`:

```sh
export NVM_DIR="/Users/cloverich/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

I commented those out, created a `~/.zshenv` file, and added those lines there. I then needed to add `nvm use iojs` (I'm using iojs in place of node presently). Think something like this is worth adding to the docs?
