### ISSUE TITLE
jshint should also look for the "jshintConfig" key in package.json for options

### ISSUE THREAD

**Issue by jakofranko** [SublimeLinter/SublimeLinter-jshint#104]
I've been banging my head against this issue for a while till I decided to come look at the code. This is a snippet from http://jshint.com/docs/cli/:

> `jshint` will look for this configuration in a number of locations, stopping at the first positive match:
The location specified with the `--config` flag
A file named `package.json` located in the current directory or any parent of the current directory (the configuration should be declared as the `jshintConfig` attribute of that file's JSON value)
A file named `.jshintrc` located in the current directory or any parent of the current directory
A file named `.jshintrc` located in the current user's "home" directory (where defined)

Looks like you're currently supporting the first and third locations of the config location, but not the second and fourth. It would be nice to be able to specify options in the package.json :)-

**Comment by kaste** [comment]
This has been fixed in https://github.com/SublimeLinter/SublimeLinter-jshint/commit/fe67fce54b5889e4a798eacc8c983d294bb4a9cb
