### ISSUE TITLE
ES6 Errors... only available in in ES6 (use 'esversion: 6')

### ISSUE THREAD

**Issue by webdevnerdstuff** [SublimeLinter/SublimeLinter-jshint#105]
OS: Win7
Sublime: v3 Build 3126
SublimeLinter: v3.8.0 +1
SublimeLinter-jshing: v1.3.0

When linting in Sublime it gives the error of "... only available in in ES6 (use 'esversion: 6')".

From what I have found and understand, that is the setting you should put in your _.jshintrc_ file. Where are you supposed to put that setting if you are not using a _.jshintrc_ file, but are using your settings files for Sublime to be more global?

The goal is to not have to create a _.jshintrc_ file for every single project, but to add it to the SublimeLinter or Sublime settings if possible, or at least where/how to do this. I have tried it in a few places without any success.

**Comment by MattRink** [comment]
I managed to get this to work on MacOS 10.12 by creating a `.jshintrc` file for my global settings in my user's home directory.

**Comment by didaquis** [comment]
> ... by creating a .jshintrc file for my global settings in my user's home directory. 

Hi @MattRink can you explain how you solved this more detailed? 
For example, what should the content of that file?

**Comment by braver** [comment]
> I managed to get this to work on MacOS 10.12 by creating a .jshintrc file for my global settings in my user's home directory.

This is basically the correct solution.

**Comment by jslmariano** [comment]
This shouldn't be closed yet as @webdevnerdstuff  have a windows 7 OS and @MattRink  was on MacOS, i think this feature does not really work on windows
