### ISSUE TITLE
How can I close warning about es6?

### ISSUE THREAD

**Issue by zhzhch335** [SublimeLinter/SublimeLinter-jshint#117]
![image](https://user-images.githubusercontent.com/13182410/41266419-5c8000d8-6e29-11e8-92b4-6415484b1a2a.png)

es6 is supported by many browsers now, and probably we use it everytime and everywhere. So could I close these warning?

**Comment by kaste** [comment]
Hi 👋 !

You need a `.jshintrc` file to configure jshint. In that file, something like this

```
{
	"esversion": 6
}
```

should do the trick.

**Comment by zhzhch335** [comment]
Thanks ! It's right!
Maybe it's useful for others:
![image](https://user-images.githubusercontent.com/13182410/41324915-012b5676-6eea-11e8-9fd5-9982a909ea38.png)

**Comment by kaste** [comment]
Cool!

**Comment by skybondsor** [comment]
This isn't working for me.

**Comment by skybondsor** [comment]
This isn't working for me. Any reason to think @zhzhch335's user settings config should look different on a Mac?

**Comment by kaste** [comment]
I don't think there's anything Windows specific here. Check for typos, I usually try the command on the command line first if it doesn't work. In the SublimeLinter settings set debug to true, then open the Sublime console (View > Console) and check which command SublimeLinter actually runs here.

**Comment by rjksn** [comment]
Might be late, but did you create a .jslint file, and insert the path instead of @zhzhch335's Windows C relative path, @skybondsor? 

I just created a .jshint in the root of the project and it did the trick.

**Comment by skybondsor** [comment]
I did indeed! Maybe I'm putting the .jshint file in the wrong place? Where should it go?

**Comment by PacoTiger** [comment]
I don't understand how to fix this problem!  Where is the *** file .jshintrc?

**Comment by rjksn** [comment]
I have the .jshintrc file in the root folder with package.json and
composer.json. Once I restarted Sublime the error was gone.

**Comment by matthewmain** [comment]
copyable text:

```
{
	"linters":{
		"jshint":{
			"args":["--config", "C:\\Users\\Administrator\\.jshintrc"]
		}
	}
}
```

**Comment by RifatMahmudno-1** [comment]
`
// SublimeLinter Settings - User
{
	"linters": {
		"jshint":{
			"args" : ["--config", "E:\\Extensions\\codeExt\\.jshintrc"],
		}
	},
}
`
This isn't working for me..
