### ISSUE TITLE
JSHint SOLVE PHP issue

### ISSUE THREAD

**Issue by Snowily** [SublimeLinter/SublimeLinter-jshint#120]
WTF... why JSHint doesnt ignore hinting when found a <?, <?= or <?php inside?

At least add an option to disable it on php files.

¿Are some solution to this? Thanks.

**Comment by Snowily** [comment]
Sorry for the WTF, too many hours working and I came across this problem once again.

I have a selector instead of an exclude to solve it:

(In sublimeintern.settings, this is not in google and it sure helps someone):

"jshint": {
"selector": "source.js - embedding.php",
}

The problem is that ignoring these files is NOT a solution, it is a WorkAround.

Make the selector more specific to ignore the <? It is not viable within the JS because they continue to show other errors.

I think this is big enough for the plugin to fix it in an appropriate way ... 

Dreamweaver also uses JSHint and solves it .. so its possible and not hard because Dreamweaver is.... ok no more WTF on here.

**Comment by kaste** [comment]
Hm, with the standard PHP syntax the selector `source.js - embedding.php` doesn't select anything, so this would be just the obscure version of excluding this file. 

What you want to select is more akin to `source.js - meta.embedded` but this will likely not produce valid js.

eslint with some plugins works probably better.

**Comment by Snowily** [comment]
with my code exclude all .php files like exclude.

source.js - meta.embedde isnt a solution because dont solve all errors (only inside embbed, its better but only in string case '<?= ?>'.

**Comment by kaste** [comment]
Extracting valid js out of a php page is probably non-trivial and out of scope. eslint has https://github.com/tengattack/eslint-plugin-php-markup which will maybe do a godd-enough job.
