### ISSUE TITLE
How can I fix Jshint(erred) in Sublime Text?

### ISSUE THREAD

**Issue by TamTH265** [SublimeLinter/SublimeLinter-jshint#121]
![Screenshot from 2019-04-23 09-16-41](https://user-images.githubusercontent.com/42565230/56547816-acd40d00-65a8-11e9-86c6-4c9d808e4151.png)

This is the first time I install jshint, how can I fix this issue?

**Comment by kaste** [comment]
Hi!

From the screenshot alone we can't tell anything. 

Please open Sublime's console (View > Show Console) for a hint/error message. If that doesn't help , enable debug mode from within the SublimeLinter settings which will print out a lot of information in said console.
