### ISSUE TITLE
WARNING: no jshint version could be extracted from: <BLANK>

### ISSUE THREAD

**Issue by Lexicality** [SublimeLinter/SublimeLinter-jshint#29]
I'm using ST3 under Windows 8.1 (x64) with node installed and set up in my path correctly. I'm trying to use this plugin, but it doesn't seem to do anything. I noticed this in my console output which presumably has something to do with it.
![](http://i.imgur.com/sY3U6ie.png)
Any suggestions as to what do? The other linters I have installed work fine.

**Comment by ganeshaditya1** [comment]
Facing the same issue in Ubuntu 14.04, Python 2.7, jshint v2.8.0

jshint --version works fine, but in debug mode sublimelinter throws this error:
"WARNING: no jshint version could be extracted from:"
