### ISSUE TITLE
nonbsp option causes error at end of files

### ISSUE THREAD

**Issue by Daniel-Hug** [SublimeLinter/SublimeLinter-jshint#34]
Notice the error on the last line (no message):
![JSHint nonbsp error in Sublime](http://i.snag.gy/HR7Dt.jpg)

My .jshintrc file:

``` json
{
    "browser": true,
    "devel": true,
    "eqnull": true,
    "camelcase": true,
    "eqeqeq": true,
    "freeze": true,
    "immed": true,
    "indent": 4,
    "latedef": true,
    "newcap": true,
    "noarg": true,
    "nonbsp": true,
    "nonew": true,
    "quotmark": "single",
    "undef": true,
    "unused": true,
    "strict": true,
    "trailing": true
}
```

Removing the `nonbsp` option eliminates the error.

**Comment by valdrinkoshi** [comment]
please update also the package.json with the latest version of jshint (the current one has a lot of false messages)
Update with this command
npm install grunt-contrib-jshint@0.11.2 --save-dev
