### ISSUE TITLE
Plugin not found (in Package Control)

### ISSUE THREAD

**Issue by tborychowski** [SublimeLinter/SublimeLinter-jshint#4]
I tried to install it via `Package Control`, but it doesn't show up.
When I clone it to my packages, on ST3 load console shows this:

```
File "D:\Applications\Sublime Text 3 x64\Data\Packages\SublimeLinter-jshint\linter.py", line 14, in <module>
    from SublimeLinter.lint import Linter, util
ImportError: No module named 'SublimeLinter.lint'
```

**Comment by jamesmehorter** [comment]
I'm also running into this issue, and none of the above suggestions have aided in a solution. I'm on OS X 10.10.1 w/ Sublime 3066. I've reverted my Sublime install (https://www.sublimetext.com/docs/3/revert.html) and even tried a fresh install; neither let's me install SublimeLinter. When I search in Package Control for 'SublimeLin' I am not given an option to install SublimeLinter. Any suggestions?

![screen shot 2015-01-12 at 3 13 39 pm](https://cloud.githubusercontent.com/assets/491189/5710138/ad7c8b16-9a6d-11e4-9431-83e373afea8c.png)

**Comment by OliverJAsh** [comment]
Same problem here as @jamesmehorter

**Comment by jamesmehorter** [comment]
Oddly enough, I tried again this morning and now SublimeLinter is showing up! Definitely feels like some sort of caching???? Super weird! 

![screen shot 2015-01-13 at 9 36 59 am](https://cloud.githubusercontent.com/assets/491189/5722167/e88f944c-9b07-11e4-9deb-58fe7d163299.png)

**Comment by thewinterwind** [comment]
same prob here, not showing up.
![image](https://cloud.githubusercontent.com/assets/2460820/7081012/edd0a1bc-df6d-11e4-90ff-c7f5e90a89dd.png)

**Comment by skj3gg** [comment]
@thewinterwind https://github.com/wbond/package_control/issues/926 this was a package control issue, and has been resolved.

**Comment by alexjlockwood** [comment]
In order to get it to show up, I had to go into my package control settings and update the following line:

"repositories": ["https://github.com/SublimeLinter/SublimeLinter-jshint"],

**Comment by kaste** [comment]
Package Control is currently down.
