### ISSUE TITLE
ISSUE: Still have "SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint'"

### ISSUE THREAD

**Issue by FRoselleck** [SublimeLinter/SublimeLinter-jshint#50]
I checked all the docs and follow the steps I could do for a whole day, but I still can't use jshint to check my errors.
Here are the information on the debug mode. Could you give me any advise?

Thanks !

startup, version: 3065 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/Zarek/Library/Application Support/Sublime Text 3/Packages
state path: /Users/Zarek/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 4
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/Zarek/Library/Application Support/Sublime Text 3/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 0 total files: 173 cache hits: 172
pre session restore time: 0.430286
using gamma: 2 (err: 6.9282)
first paint time: 0.48985
startup time: 0.50638
found 1 files for base name Default.sublime-theme
theme loaded
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-jshint.linter
loaded 837 snippets
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/gh/r03bz0zj52v5v_z__47nz0th0000gn/T/SublimeLinter3 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/local/bin/node
/usr/local/bin/npm
/usr/local/bin/jshint
/usr/local/lib/node_modules/jshint
/usr/local/lib/node_modules/jshint/bin/jshint
/usr/local/bin
/Library/Frameworks/Python.framework/Versions/3.4/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/bin
/opt/X11/bin
/usr/local/bin/jshint
/usr/local/lib/node_modules/jshint/bin/jshint
/usr/local/lib/node_modules/jshint
 
SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
found 3 files for base name Main.sublime-menu
Package Control: Skipping automatic upgrade, last run at 2014-09-29 22:44:08, next run at 2014-09-29 23:44:08 or after

**Comment by FRoselleck** [comment]
Not yet... I tried install jshint in 
"ZarekLinzdeMacBook-Pro:~ Zarek$ npm install jshint -g"
or 
"bash-3.2$ npm install jshint -g"

Neither of them can install jshint.  
It said:
npm ERR! Error: EACCES, mkdir '/Users/Zarek/.npm/jshint/2.6.0'
npm ERR!  { [Error: EACCES, mkdir '/Users/Zarek/.npm/jshint/2.6.0']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/Zarek/.npm/jshint/2.6.0' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "jshint" "-g"
npm ERR! cwd /Users/Zarek
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Zarek/.npm/jshint/2.6.0
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/Zarek/.npm/jshint/2.6.0'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Zarek/npm-debug.log
npm ERR! not ok code 0



Anyway, thank you very much

**Comment by AlexKovalevych** [comment]
@FRoselleck try `sudo npm install jshint -g`

**Comment by briandela** [comment]
@FRoselleck This looks like an issue with your NPM install. NPM should not require sudo to install things. 

Have a look at http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo or http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/ for help on fixing NPM. Then `npm install jshint -g` should work.
