### ISSUE TITLE
Add configuration to stop lint from jumping to first error

### ISSUE THREAD

**Issue by eboto** [SublimeLinter/SublimeLinter-jshint#51]
Working on a project with a lot of jshint errors that I can't tackle all it once. It really interrupts my flow when saving the file automatically jumps my cursor to the first error.

Is there a way to configure this linter to _not_ jump my cursor straight to the error line?

**Comment by jonkafton** [comment]
Thanks David. Good call!

**Comment by jminnick** [comment]
nice @davidfooks

**Comment by rgant** [comment]
@davidfooks Thanks that was very helpful.

**Comment by geedamed** [comment]
@davidfooks Thank you!

**Comment by rgant** [comment]
@davidfooks 
I was also annoyed by how canceling the quick_panel by clicking inside of the page caused the page to scroll and jump and I would end up clicking in the wrong place.

So I've also commented out this else block in the select_error function in commands.py:

```
        # else:
        #     self.view.set_viewport_position(self.viewport_pos)
        #     self.view.sel().clear()
        #     self.view.sel().add_all(self.selection)
```

**Comment by airtonix** [comment]
commenting here to complain about this behaviour. it's annoying let me turn it off without turning off show errors on save.

**Comment by sethbro** [comment]
👍 Would love for this to be a config setting. The jump frequently hijacks my train of thought.

**Comment by dnunes** [comment]
Just so it is clear: would you guys want to show the panel, make the cursor stay where it is but then jump around as you select the errors? I'm not sure it's even useful anymore with the new panel, but a simple fix would be to add a "Error list:" dummy entry at the top of the list (on your fork, of course :)) that wouldn't point anywhere in the code. That would keep all the good behavior while also not making the cursor jump as soon as the panel shows up.
