### ISSUE TITLE
Can I lint a directory/project?

### ISSUE THREAD

**Issue by Tain101** [SublimeLinter/SublimeLinter-jshint#58]
I like the ability to find unused code, but a lot of my functions are being declared in file A, and called in file B.

I can't find anyway to look at both files for declarations/use.

**Comment by skj3gg** [comment]
No, you can't. This is actually a problem with JSHint itself more than SL-jshint, though I understand the pain.

**Comment by Tain101** [comment]
ahh, thanks.
