### ISSUE TITLE
Cant find plugin in package control

### ISSUE THREAD

**Issue by mort3za** [SublimeLinter/SublimeLinter-jshint#59]
Hi,
I installed sublimelinter by package control but still there is no SublimeLinter-jshint plugin in the list of packages for install.
Also i checked disabled plugins, There's nothing.
How can i find this plugin in package control?!

**Comment by sjelfull** [comment]
I have the same problem. You can get around it by adding the repository manually:

1) Open Command palette, and select Package Controll: Add repository
2) Add the GitHub url: https://github.com/SublimeLinter/SublimeLinter-jshint
3) Select Package Control: Install Package. It will then fetch the repo info.
4) If you search for jshint, the plugin should show up. Install as normal.

**Comment by mort3za** [comment]
I did it but i don't see any action after selecting `SublimeLinter-jshint` in the install plugins palete. Just palete will close and there isn't any error or success message.

**Comment by mokkabonna** [comment]
This is probably more an issue with package control that the code in this plugin.
