### ISSUE TITLE
global configurations not work

### ISSUE THREAD

**Issue by ajshortt** [SublimeLinter/SublimeLinter-jshint#60]
I'm trying to apply some global settings to keep my js tidy. I tried following the documentation and still not working.

"linters": {
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "camelcase": true
            },

example here is the camelcase setting.

Any idea?

**Comment by mokkabonna** [comment]
You can not set jshint options this way. This is for the linter pligin settings. http://sublimelinter.readthedocs.org/en/latest/linter_settings.html

If you want global settings, I suggest you put a .jshintrc file in your home directory. With this in it:

```
{
  camelcase:true
}
```

See more how jshint configuration works here:
http://jshint.com/docs/
