### ISSUE TITLE
Support Babel

### ISSUE THREAD

**Issue by gabrielecirulli** [SublimeLinter/SublimeLinter-jshint#62]
[Babel (previously 6to5)](http://babeljs.io/) is very useful to transform your ES6 JavaScript into ES5 and has other neat features like JSX transformation. There's a neat bundle for Sublime Text which allows it to support the new syntax: https://github.com/babel/babel-sublime

Sublimelinter-jsxhint has already added support by including the `'javascript (babel)'` definition: https://github.com/SublimeLinter/SublimeLinter-jsxhint/blob/master/linter.py#L25

Would it be possible to add it here too?

**Comment by ms88privat** [comment]
+1

**Comment by younes0** [comment]
Not sure to understand your request @gabrielecirulli but have you set the jshint "esnext" option to true to make jshint supports ES6 ?

**Comment by kudos** [comment]
@younes0 `javascript (babel)` is an ES6 syntax highlighter which this linter package doesn't recognise as being Javascript even though `jshint` can lint ES6 too.

**Comment by younes0** [comment]
thanks @kudos 
I think that instead of adding `javascript (babel)` as a default syntax, we should look towards [this PR](https://github.com/SublimeLinter/SublimeLinter-jshint/pull/56) : it allows you to override the syntax list (less opiniated option)

**Comment by kudos** [comment]
@younes0 I think the best solution is to use the `syntax_map` setting in SublimeLinter, adding `"javascript (babel)": "javascript"` to that array tells this linter to lint that syntax type. The problem is that it isn't well documented.

**Comment by younes0** [comment]
@kudos thanks for the tip

**Comment by Ambroos** [comment]
Using syntax map isn't ideal either.

I use `javascript (babel)` for both ES6 Javascript as well as JSX. By mapping `javascript (babel)` to `javascript`, I can now no longer use sublimelinter-jsxhint, since it doesn't recognize simple `javascript` files.

Just adding `javascript (babel)` really isn't the worst idea as long as there isn't a way to override the syntax list. When it comes to both ES6 and JSX it's by far the best syntax highlighting there is right now anyway.

**Comment by LeoAJ** [comment]
+ 1

**Comment by navdeepsb** [comment]
@younes0 where to set the `esnext` option to true? i am using Sublime Text 3 on Windows and I set this option in the `.jshintrc` file in SublimeLinter-jshint.sublime-package but I keep getting the "use esnext option" warning.

**Comment by younes0** [comment]
@navdeepsb the `.jshintrc` file should be located your javascript root folder:
```json
{
  "esnext": true,
  "asi": false,
  "boss": false,
  "camelcase": false,
  "curly": false,
  "eqeqeq": false,
  "eqnull": false,
  "es5": false,
  "evil": false,
  "expr": true,
  "forin": false,
  "funcscope": false,
  "immed": false,
  "indent": 2,
  "latedef": false,
  "loopfunc": false,
  "maxerr": 7,
  "newcap": false,
  "node": true,
  "nonew": false,
  "plusplus": false,
  "quotmark": "false",
  "regexdash": false,
  "shadow": false,
  "strict": false,
  "sub": false,
  "supernew": false,
  "trailing": false,
  "undef": false,
  "unused": false,
  "white": false
}
```

**Comment by navdeepsb** [comment]
got it @younes0. created a `.jshintrc` file in my project root folder with `esnext` set as true, it worked, thanks...

**Comment by MatixYo** [comment]
How to set it up so it works globally? Not just in project that you put .jshintrc to. I added `"esnext": true` to _SublimeLinter.sublime-settings_ but it didn't work.

**Comment by younes0** [comment]
Install https://github.com/roadhump/SublimeLinter-eslint

How to set it up so it works globally? Not just in project that you put
.jshintrc to. I added "esnext": true to *SublimeLinter.sublime-settings*
but it didn't work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SublimeLinter/SublimeLinter-jshint/issues/62#issuecomment-230170500>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA2FGrtN2jsgqriNeQ3_uFUT-FSoAaqgks5qSAw-gaJpZM4DhZSM>
.

**Comment by DiegoZoracKy** [comment]
Just to add. Probably you want to use `"esversion": 6` instead of `"esnext": true`.
_

> Warning This option has been deprecated and will be removed in the next major release of JSHint. Use esversion: 6 instead.
> This option tells JSHint that your code uses ECMAScript 6 specific syntax. Note that not all browsers implement these features.
> 
> More info:
> 
> Specification for ECMAScript 6

_

http://jshint.com/docs/options/#esnext

**Comment by rainabba** [comment]
@DiegoZoracKy That suggestion is lacking for the same reason I'm here and I imagine @navdeepsb; I can't find any explanation as to where we want to 'use "esversion": 6'  :/

Can you explain where this option should be placed? Sorry if it seems obvious, but I just followed the directions to install everything and haven't used this linter before so please assume nothing other than a knowledge of how to edit Sublime Package Settings in general.

**Comment by DiegoZoracKy** [comment]
@rainabba Take a look here where it is explained how to configure the plugin using a `.jhintrc` file:

https://github.com/SublimeLinter/SublimeLinter-jshint#settings

The option `"esversion": 6` or `"esnext": true` should be placed at this file, as it is shown in this comment: 

https://github.com/SublimeLinter/SublimeLinter-jshint/issues/62#issuecomment-141921622

**Comment by robstarbuck** [comment]
As answered on [stack](http://stackoverflow.com/a/31095500/999248) 

You can create a `.jshintrc` in your project folder, it will be read by the linter as a json source file.

To use esnext option, 

    {
        "esnext": true
    }

You will probably need to reopen your JS file to be able to see the new changes.

**Comment by Kein** [comment]
is there any way to disable jshint for JSX files? I tried using .jshintignore in project root folder but it does not work.
