### ISSUE TITLE
jshint error in shell only when using SublimeLinter-jshint

### ISSUE THREAD

**Issue by janusch** [SublimeLinter/SublimeLinter-jshint#64]
Hey,
I get the following error on an Linux/Ubuntu with ST build 3065:

```
Writing file /home/user/app/zap.js with encoding UTF-8 (atomic)
SublimeLinter: jshint: zap.js ['/home/user/bin/jshint', '--verbose', '--filename', '@', '--config', '/home/user/app/.jshintrc', '-']
SublimeLinter: jshint output: 
shell.js: internal error 
TypeError: Object #<Object> has no method 'existsSync'
 ...
```

I have looked at this issue which might be related: https://github.com/SublimeLinter/SublimeLinter-jshint/issues/19 

The suggested fixes did not work.

Also, the path I set in SublimeLinter.sublime-settings is not the same as specified in the error message. I changed path in both user settings and SublimeLinter settings, but the changes are not reflected.

jsHint runs fine from the command line and with the sublime text plugin jsHint gutter. I would just prefer to use SublimeLinter for all my linting.

Would be wonderful if you had some input on how to resolve it, especially because it works in the other jsHint ST3 plugin.

**Comment by braver** [comment]
Closing due to age.
