### ISSUE TITLE
latest update of Sublime text 3 breaks SublimeLinter-jshint

### ISSUE THREAD

**Issue by alanquigley** [SublimeLinter/SublimeLinter-jshint#65]

**Comment by mokkabonna** [comment]
I have no problems with the lastest version of sublime text 3 (build 3080)

Can you provide more information?

**Comment by alanquigley** [comment]
Hmmm, started working again after a computer restart. Must have been a
problem with jshint.

**Comment by wilsonmiz** [comment]
Hey guys, I got this problem on ST3 3084 with jshint 2.6.3. How to troubleshoot?

**Comment by leifcr** [comment]
@alanquigley shouldn't the issue be closed then?
