### ISSUE TITLE
config .jshintrc overrides settings precedence

### ISSUE THREAD

**Issue by jcrben** [SublimeLinter/SublimeLinter-jshint#66]
I expected that a custom .jshintrc passed into args would act as a global setting, but it seems to be overriding even a .jshintrc which is directly in the folder being edited. Is this the intended behavior?

I would like to place my global settings somewhere besides my home directory to avoid cluttering it with configuration files. Similarly, in Linux the trend is for configs to be located under in the ~/.config directory rather than directly in the home.

**Comment by claudiosmweb** [comment]
+1

**Comment by darsain** [comment]
This is the same problem as in #38 that was supposedly fixed by #46, but seeing as I have the same issue, it doesn't seem like it worked.

I run on windows.

**Comment by jcrben** [comment]
It sounds like there's been work to address this issue, plus I don't use Sublime much these days...
