### ISSUE TITLE
SublimeLinter-jshint not working in JavaScript (DOM)

### ISSUE THREAD

**Issue by auz9** [SublimeLinter/SublimeLinter-jshint#67]
An observation:
Can anyone confirm if SublimeLinter-jshint is not meant to work with JavaScript Ultimate>JavaScript (DOM) syntax?  When switched over to JavaScript Ultimate>JavaScript, it works fine.
Another package JSHint Gutter is able to run with either.

SublimeText ver 3083
SublimeLinter-jshint ver 1.2.1
jshint ver 2.6.3
nodeJs ver 0.10.25
Linux Mint 17 kernel 3.13.0-48.80

--

**Comment by mrliptontea** [comment]
+1 - same here

SublimeText build 3084
SublimeLinter-jshint 1.2.1
jshint v2.7.0
node v0.12.2
Windows 8.1 x64

I tried adding syntax map to user config:

```json
"syntax_map": {
    "JavaScript (DOM)": "JavaScript"
}
```

But it didn't change anything.

**Comment by mrliptontea** [comment]
@auz9 I figured it out, but this is a little bit dumb :neutral_face: 

I was right in the beginning to add it to syntax map, but it must be all in lowercase, so like this:

```json
"syntax_map": {
    "javascript (dom)": "javascript"
}
```

This is in fact stated in the [documentation](http://sublimelinter.readthedocs.org/en/latest/global_settings.html?highlight=syntax_map#syntax-map). I'm for closing this issue.

**Comment by auz9** [comment]
This is great. Thanks for figuring out.

**Comment by volchub** [comment]
thanks! :)
