### ISSUE TITLE
How to install jshint on windows?

### ISSUE THREAD

**Issue by thehung2224** [SublimeLinter/SublimeLinter-jshint#68]
Hi,

I'm trying to make it work, I have to install Node.js & jshint on windows. I have installed Node.js but I don't know how to install jshint. It only show the way install for MAC on the homepage, neither internet.

    npm install -g jshint

Hope anyone can tell me how to install on windows and make the plugin works. Thank for any helps.

Best Regards,
Hung The.

**Comment by mokkabonna** [comment]
This is exactly how you install in on windows, what errors do you get when installing it?

**Comment by thehung2224** [comment]
Hi,

Thank you for reply. I resolved my issue.

Regards,
Hung The.
