### ISSUE TITLE
Support for Django templates

### ISSUE THREAD

**Issue by dturner** [SublimeLinter/SublimeLinter-jshint#69]
Here's my use case: 

I'm using Sublime Text 3 and SublimeLinter-jshint for JavaScript code linting. This works great for .js files, however, when I try to lint on a Django template file (.html extension) jshint reports errors e.g.

```
Expected a string and instead saw %
```

Which is caused by django's open template tag: `{%`

My workaround is to use the following linter config within SublimeLinter.sublime-settings:

```
"jshint": {
        "@disable": false,
        "args": ["--extract=auto"],
        "excludes": []
} 
```

My Django template file must always start with a comment e.g. `<!-- Django template - for linter -->`. This way jshint correctly detects it as an HTML file and extracts the JavaScript.

What would be really nice is if Django templates were supported out of the box without needing to add extra code to each file. One idea is to have a separate jshint linter config for html files (which would include the --extract=always argument) and one for normal JS files (which wouldn't).

**Comment by dturner** [comment]
Related: https://github.com/jshint/jshint/issues/2347

**Comment by xoneco** [comment]
This would be wonderful!

**Comment by braver** [comment]
We use scope selectors now to transparently support embedded syntaxes everywhere, as long as the main syntax definition is correct. This probably works by now, perhaps with some tweaks to the selector setting.
