### ISSUE TITLE
jshint not linting at all.

### ISSUE THREAD

**Issue by zvodd** [SublimeLinter/SublimeLinter-jshint#71]
I followed the correct installation procedure, etc.
The issue might be related to another plugin I have installed.
Edit: The plugin: "JavaScript Ultimate" changes most javascript  views to the syntax 'javascript (dom)'.

https://github.com/zvodd/SublimeLinter-jshint/commit/2a96d77b49cdba436d55473ca7670ad03987abf0

If it's agreeable, it should be changed in all the JavaScript linter plugins.

**Comment by PauloSegundo** [comment]
Not linting here too. My syntax is set to JavaScript.

**Comment by PauloSegundo** [comment]
Getting the error: SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' 

But i have jshint installed:

DarkMacBook:CargoTrail paulosegundo$ jshint --version
jshint v2.8.0

DarkMacBook:CargoTrail paulosegundo$ which jshint
/Users/paulosegundo/.nvm/versions/io.js/v2.1.0/bin/jshint

Don't know what is the problem.

**Comment by rmilesson** [comment]
I have the same issue, where it's not linting at all. I can see in the config that it's found the correct `.jshintrc`-file, it's not disabled and it's working if I run `jshint` from command line. It worked perfectly yesterday.

I get no errors and I've cleared the cache. Is there a good way to debug this?

**Comment by Wenape** [comment]
Same here. The linter just stops working sometimes without reporting anything.

**Comment by zvodd** [comment]
Actually it doesn't require an update to this repo as SublimeLinter actually has a setting to fix it - at least the issue I was having.

If you are using the "Javascript Ultimate" package it changes the name of the syntax that sublime is using when in .js and .html files.  - Possibly some other javascript related packages do the same - .
I found in the documentation you can remap the additional syntax names to the supported syntax names for SublimeLinter.

http://www.sublimelinter.com/en/latest/global_settings.html#syntax-map

In Sublime, go to Preferences -> Package Settings -> SublimeLinter -> Settings - User.
Then add the entries into the Json settings under "syntax_map":

````
{ 
    "user": {
         ...
         "syntax_map":{
             ...
            "javascript (dom)": "javascript",
            "javascriptnext": "javascript"
         }
}
````

You may also need to add the node npm directory under {"user":{"paths": {"yourOS": [ "/dir/to/nodeNpm" ] }}}

**Comment by braver** [comment]
We use the selector setting now, so you don’t need to edit the syntax map anymore.
