### ISSUE TITLE
Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by nodesocket** [SublimeLinter/SublimeLinter-jshint#76]
Confirmed jshint is installed globally via npm. Console reports:

````shell
SublimeLinter: jshint activated: /usr/local/bin/jshint 
SublimeLinter: ERROR: could not launch ['/usr/local/bin/jshint', '--verbose', '--filename', '/Users/justin/Sites/healthy/healthy.js', None, '-'] 
SublimeLinter: reason: Can't convert 'NoneType' object to str implicitly 
SublimeLinter: PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
````

Running:

````shell
➜  ~  node -v
v0.12.7
````

**Comment by nodesocket** [comment]
Any ideas?

**Comment by nodesocket** [comment]
`jshint` is in the PATH for Sublime.

````
➜  ~  which jshint
/usr/local/bin/jshint
````

**Comment by shopapps** [comment]
did you ever get this figured out?  I have the same issue on apple mac.  Manually running the command works ok

**Comment by nodesocket** [comment]
@shopapps, Unfortunately not. Still can't use jshint in Sublime.

**Comment by shopapps** [comment]
I did some digging and found that my error was due to having something set in the **args** option in the user settings file  **SublimeLinter.sublime-settings** that shouldn't be there  so i defaulted mine to:

    "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },

and then all started working again!

**Comment by nodesocket** [comment]
@shopapps, thanks for the suggestion, that works. Here is the fix.

Open up: Preferences => Package Settings => SublimeLinter

Find the `jshint` json section.

Remove any arguments. I had:

````
{
    "esnext": true
 }
````

Which I thought was a valid option, but it appears they changed the API and removed it.
