### ISSUE TITLE
warning jshint deactivated cannot locate 'jshint'

### ISSUE THREAD

**Issue by artexanis** [SublimeLinter/SublimeLinter-jshint#77]
I'm trying for two days now to get this working, but I'm clearly missing something.

Console output on sublime start:

> DPI scale: 1
> startup, version: 3083 linux x64 channel: stable
> executable: /opt/sublime_text/sublime_text
> working dir: /
> packages path: /home/hans/.config/sublime-text-3/Packages
> state path: /home/hans/.config/sublime-text-3/Local
> zip path: /opt/sublime_text/Packages
> zip path: /home/hans/.config/sublime-text-3/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 0.066605
> startup time: 0.116957
> first paint time: 0.120247
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_file_settings
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.quick_panel
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-ssl-linux
> Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
> reloading plugin 0_package_control_loader.02-bz2
> reloading plugin Package Control.Package Control
> reloading plugin Package Control.bootstrap
> reloading plugin SideBarEnhancements.SideBar
> reloading plugin SideBarEnhancements.SideBarAPI
> reloading plugin SideBarEnhancements.SideBarDefaultDisable
> reloading plugin SublimeLinter-contrib-htmlhint.linter
> SublimeLinter: htmlhint linter loaded 
> reloading plugin SublimeLinter-csslint.linter
> SublimeLinter: csslint linter loaded 
> reloading plugin SublimeLinter-html-tidy.linter
> SublimeLinter: htmltidy linter loaded 
> reloading plugin SublimeLinter-jshint.linter
> SublimeLinter: jshint linter loaded 
> reloading plugin SublimeLinter-json.linter
> SublimeLinter: json linter loaded 
> reloading plugin SublimeLinter-php.linter
> SublimeLinter: php linter loaded 
> reloading plugin SublimeLinter-xmllint.linter
> SublimeLinter: xmllint linter loaded 
> reloading plugin SublimeLinter.commands
> reloading plugin SublimeLinter.sublimelinter
> plugins loaded
> SublimeLinter: debug mode: off 
> Package Control: Skipping automatic upgrade, last run at 2015-08-14 10:15:15, next run at 2015-08-14 11:15:15 or after

if I open a js file this line appears in console:

> SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint'

output of 'which jshint' in terminal:

> /home/hans/.npm-packages/bin/jshint

my user settings:

> {
> "color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
> "font_size": 9,
> "ignored_packages":
> [
> "Vintage"
> ],
> "rulers":
> [
> 120
> ],
> "tab_size": 2,
> "paths": {
> "linux": ["/home/hans/.npm-packages/bin/jshint"],
> "osx": [],
> "windows": []
> }
> }

I also tried:

> /home/hans/.npm-packages/bin
> /home/hans/.npm-packages/bin/

jshint was globally installed with

> npm install -g jshint #wihout sudo!

output of 'jshint -v':

> jshint v2.8.0

I'm completely in the dark of what went wrong. In my previous install it worked without problems.(had to reinstall due to graphics problems (and switched to debian instead of ubuntu))

I would be very happy if someone can point me to a solution.

Thanks!

**Comment by artexanis** [comment]
bump

**Comment by auz9** [comment]
Hi, I too had been battling this issue for a while and is now resolved for me.
We all know the path-to-jshint MUST be visible to ST3 sublimeLinter.
In the KDE, and consequently, the ST3 App icon in the KMenu does not handle the npm path-to-jshint. 

My workaround was to change the KMenu App Start Command to
```
PATH=$PATH:/$HOME/.npm-packages/bin exec /opt/sublime_text/sublime_text "$@"
```
