### ISSUE TITLE
Extends not working?

### ISSUE THREAD

**Issue by raix** [SublimeLinter/SublimeLinter-jshint#78]
When adding "extends" linting breaks the sublimeLinting, running jshint from command line works fine.
```
{
  "extends": "../../.jshintrc",
  "globals": {
    // ..
  }
}
```

**Comment by arxpoetica** [comment]
The `"extends"` property does not work for me either—where it DOES work correctly w/ [JSHint Gutter](https://github.com/victorporof/Sublime-JSHint).

**Comment by mokkabonna** [comment]
This should work in theory, since all we do is pass in "--config /path/to/first/.jshintrc" to jshint. and what jshint does with that is up to jshint. Maybe jshint itself does not work when called in this way. Care to test?

**Comment by mokkabonna** [comment]
I just tried this, and it's working as expected for me. REmember to close and open files after editing jshintrc

**Comment by mokkabonna** [comment]
If lining breaks altogether I suspect non existing file or syntax error in the json

**Comment by raix** [comment]
Our regular jshint works fine both locally and on ci, but not in sublime
