### ISSUE TITLE
ES6/7 support

### ISSUE THREAD

**Issue by evanplaice** [SublimeLinter/SublimeLinter-jshint#79]
With the latest node update, I've switched to writing code in es5/6.

For the es5 features, the linter complains that I need to enable esnext.

I tried modifying SublimeLinter.sublime-settings to include:

``` json
{
    "user": {
        "jshint": {
            "es5": true,
            "esnext": true
        {
    {
{
```

With no luck. Is there some other place I can set es5/esnext as the default in Sublime.

In addition are 'template literals' supported in esnext yet. The linter is currently marking them as errors.

Sorry if these are dumb questions. I tried to follow what I could find in the documentation first.

**Comment by nicbarker** [comment]
+1

**Comment by evanplaice** [comment]
@nicbarker That'll work as a temporary stopgap but what I'm really looking for is a means to configure `"esnext": true` as the default for Sublime Text. 

I use .jshint to denote per-project exceptions to the default.

**Comment by TylerBre** [comment]
If you want to make it global, register it as command line args in the jshint block of your Sublime Linter user settings: 

```
"jshint": {
    "@disable": false,
    "args": ["--esversion", "6"],
    "excludes": [],
}
```

Now sublime linter will lint es6 by default. You can override this with a .jshint file, which I think is better behavior.

**Comment by TylerBre** [comment]
If you want global jshint options, you can place a .jshint file in your user's home directory, or you can pass a config file as an argument (via the sublime linter settings).

http://jshint.com/docs/cli/

**Comment by evanplaice** [comment]
@TylerBre I'll just configure it from my home directory.

The point of posting the issue is that the option can't be set via the SublimeLinter settings. Maybe that's not desirable for some reason I'm not aware of.

**Comment by rafapaulin** [comment]
Any chance to make this work with the [EcmaScript-Sublime](https://github.com/bathos/Ecmascript-Sublime) syntax?
