### ISSUE TITLE
Reasoning behind nvm initialization in .zshenv and not .zshrc?

### ISSUE THREAD

**Issue by cdl** [SublimeLinter/SublimeLinter-jshint#82]
Hey there,

Wondering what the reasoning behind requiring `nvm` initialization when using `zsh` to be in `.zshenv` instead of `.zshrc`?

The latest OS X update causes things to act up when `nvm` initialized in `.zshenv` instead of `.zshrc` (basically, PATH is no longer fully initialized at the time that `.zshenv` is sourced).

See: https://github.com/Homebrew/homebrew/issues/44997.

**Comment by jjeaton** [comment]
+1, after upgrading to El Capitan, every new terminal session starts with this:

```
/Users/josh/.zshenv:4: command not found: brew
/Users/josh/.zshenv:source:4: no such file or directory: /nvm.sh
```

**Comment by mokkabonna** [comment]
Solved by https://github.com/SublimeLinter/SublimeLinter-jshint/pull/97
