### ISSUE TITLE
Scope inside "If statement"

### ISSUE THREAD

**Issue by dim2k2006** [SublimeLinter/SublimeLinter-jshint#83]
Jshint shows "Error: 'c' used out of scope, Line 81, Column 1" , If i declare variable inside "If statement" and then try to use this variable outside this statement . Is it correct?

https://jsfiddle.net/s8mfo6rj/

**Comment by mokkabonna** [comment]
It is correct behaviour. You need to declare it outside. You can still assign to it inside the if, but not declare it. (unless you change your setting ofc)
