### ISSUE TITLE
jshint stopped linting

### ISSUE THREAD

**Issue by netrounds-oleg-b** [SublimeLinter/SublimeLinter-jshint#86]
Some time ago JSHint has stopped linting completely. SublimeLinter has been installed, PEP8, CSSlint - work fine. But JSHint - doesn't. No errors in console. Node.js installed and operational.

Any suggestions how to debug this?

**Comment by codeHamster9** [comment]
i have the same issue ...
this is happening to me on the sublime dev-builds :(
the stable build seems to be working (3103) 
tried uninstall/install the linter no luck ...
again only with jshint other linters work fine.

**Comment by codeHamster9** [comment]
problem solved it appears i had another package installed (sinon)
that changed the language/syntax to something other then javascript
after removing the package jshint is back! :)

you can use this command to determine your current syntax -
`sublime.active_window().active_view().settings().get('syntax')`

**Comment by netrounds-oleg-b** [comment]
just to confirm @codeHamster9 answer - the problem for me was another syntax-checking package installed in Sublime Linter. The idea is that another package changes syntax-schema somehow making the linter unable to actually check things.

**Comment by mokkabonna** [comment]
Too little info to debug.
