### ISSUE TITLE
Wrong line/col highlighted

### ISSUE THREAD

**Issue by mjmasn** [SublimeLinter/SublimeLinter-jshint#87]
Line is off by 1, column depends on the previous line but off by at least 1...

<img width="553" alt="screen shot 2016-03-16 at 22 43 38" src="https://cloud.githubusercontent.com/assets/2977095/13831030/98107cbc-ebc8-11e5-9a61-e4e69158e981.png">
<img width="188" alt="screen shot 2016-03-16 at 22 43 27" src="https://cloud.githubusercontent.com/assets/2977095/13831031/98258daa-ebc8-11e5-9c54-3cce23df9031.png">

**Comment by mokkabonna** [comment]
Cant reproduce this on the test.js file
![image](https://cloud.githubusercontent.com/assets/230877/23026559/efb3b036-f461-11e6-811f-094faae283a8.png)

Can you paste the whole file? Or a simple testcase that proves it.
