### ISSUE TITLE
Output results to a panel

### ISSUE THREAD

**Issue by grrowl** [SublimeLinter/SublimeLinter-jshint#89]
I'd love if Sublime Linter could output errors and warnings to a panel at the bottom of the window, a bit like how SublimeGit displays commit output.

![image](https://cloud.githubusercontent.com/assets/907140/14417127/e05ea76a-fff4-11e5-98a1-6dcb35628038.png)

What are the chances of this being possible?

**Comment by mokkabonna** [comment]
Would need to be implemented in https://github.com/SublimeLinter/SublimeLinter3
