### ISSUE TITLE
node js global flag -g doesn't work without sudo on El Capitan

### ISSUE THREAD

**Issue by ortonomy** [SublimeLinter/SublimeLinter-jshint#90]
I don't know if this should be in the wiki / install page, but I found that using 

`npm install xxxx -g` 

will not work unless using sudo due to El Capitan's stricter controls on where scripts can run. Perhaps a note to people trying to install and getting errors would be nice.

**Comment by mokkabonna** [comment]
This is platform specific. And related to npm, so not relevant.
