### ISSUE TITLE
Error while plugin runs

### ISSUE THREAD

**Issue by Skriptach** [SublimeLinter/SublimeLinter-jshint#93]
Console output

> reloading plugin SublimeLinter-jshint.linter
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 78, in reload_plugin
>     m = importlib.import_module(modulename)
>   File "./python3.3/importlib/**init**.py", line 90, in import_module
>   File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
>   File "/opt/sublime_text/sublime_plugin.py", line 658, in load_module
>     exec(compile(source, source_path, 'exec'), mod.__dict__)
>   File "linter in /home/skripatch/.config/sublime-text-3/Installed Packages/SublimeLinter-jshint.sublime-package", line 14, in <module>
> ImportError: No module named 'SublimeLinter'

subl -v
Sublime Text Build 3114

**Comment by braver** [comment]
A lot has happened since, we probably did something to fix this by now. Or you probably just didn't install the SublimeLinter core package.
