### ISSUE TITLE
SublimeLinter-jshint disappeared from sublime text 3 repository

### ISSUE THREAD

**Issue by nbulgarini** [SublimeLinter/SublimeLinter-jshint#95]
I can't find SublimeLinter-jshint anymore in sublime text 3 repositories. Why?

**Comment by xdream86** [comment]
I also no find sublimelinter-jshint, just have sublimelinter-jsXhint.

**Comment by shimizust** [comment]
Same here, cannot locate SublimeLinter-jshint on Sublime 3 (3126)

**Comment by mokkabonna** [comment]
I have no problem finding it. 

![image](https://cloud.githubusercontent.com/assets/230877/23025583/b8a5cfa0-f45e-11e6-856e-614aeb153138.png)

Try again? Maybe some issues with package manager.
