### ISSUE TITLE
jshinting across multiple files

### ISSUE THREAD

**Issue by pliablepixels** [SublimeLinter/SublimeLinter-jshint#98]
Hi there, thanks for this lovely plugin.

Is there a way I can jshint multiple files?
thanks

**Comment by mokkabonna** [comment]
Nope, you need to define globals if you leak variables from one file to another.

**Comment by pliablepixels** [comment]
That is not what I mean. I'm asking if I can select multiple JS files and do a jshint for all of them at once. Right now, I have to tap on each file and do a 'lint this view"
